// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingTools.DAL;

namespace TradingTools.DAL.Migrations
{
    [DbContext(typeof(TradingToolsDbContext))]
    [Migration("20210929010004_CreateTradingToolsDB")]
    partial class CreateTradingToolsDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TradingTools.Trunk.Entity.CalculatorState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Capital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyInterestRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("DayCount")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryPriceAvg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LEP_ExitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LEP_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Leverage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PEP_ExitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PEP_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceDecreaseTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PriceIncreaseTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ReasonForEntry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("CalculatorStates");
                });
#pragma warning restore 612, 618
        }
    }
}
